#!/bin/sh
# usage: capitalize word
# write word to stdout w/ first character upcased
first_char=`echo $1 | sed 's/^\(.\).*/\1/' | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
echo ${first_char}`echo $1 | sed 's/^.//'`
