#!/bin/sh

# This is a simple utility for Cygwin/Mingw which is useful when running the SWIG
# test-suite through Visual Studio. If the output from the test-suite is piped
# through this utility, it will filter the junk that the compiler outputs to stdout.
# Typical usage: make check | vcfilter

# dos2unix needed for ^ and $ to work.
2>&1 dos2unix | grep -v -e "\.cxx$" -e "\.c$" -e "^   Creating library" -e "^Generating Code"

