#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/..

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'truncated=false speechTrain=[reader=[nbruttsineachrecurrentiter=2]] speechTrain=[SGD=[epochSize=2560]] speechTrain=[SGD=[maxEpochs=2]] speechTrain=[SGD=[numMBsToShowResult=1]] speechTrain=[SGD=[momentumAsTimeConstant=0:189.8]] modelSelector=0 shareNodeValueMatrices=true' || exit $?
