#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/..

# cntkrun <CNTK config file name> <additional CNTK args>
# BUGBUG: temporarily disabled shareNodeValueMatrices=true since criterion nodes somehow are shared
cntkrun cntk.cntk 'Truncated=false speechTrain=[reader=[nbruttsineachrecurrentiter=2]] speechTrain=[SGD=[epochSize=2560]] speechTrain=[SGD=[maxEpochs=2]] speechTrain=[SGD=[numMBsToShowResult=1]] shareNodeValueMatrices=false' || exit $?
