#!/bin/bash

. $TEST_DIR/../run-test-common

cntkrun ResNet110_CIFAR10.cntk "forceDeterministicAlgorithms=true traceLevel=0 stderr=- TrainConvNet=[SGD=[epochSize=512,minibatchSize=32,maxEpochs=3,numMBsToShowResult=8,learningRatesPerMB=0.128]]"
