#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

DeleteModelsAfterTest=0
# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun lstm.bs 'forceDeterministicAlgorithms=true makeMode=false' || exit $?
echo === Deleting last epoch data
rm $TEST_RUN_DIR/models/*.dnn