#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/..

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'speechTrain=[SGD=[momentumAsTimeConstant=0:6074.9]] modelSelector=0' || exit $?
