#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../../DNN/ParallelBM
ConfigDir=$TEST_DIR/$OriginalTestDir
LogFileName=stderr
Instances=2
NumCPUThreads=$(threadsPerInstance $Instances)

checkOriginalBaseline $TEST_DIR $OriginalTestDir

# cntkmpirun <MPI args> <CNTK config file name> <additional CNTK args>
cntkmpirun "-n $Instances" cntk.cntk "numCPUThreads=$NumCPUThreads precision=double speechTrain=[SGD=[ParallelTrain=[parallelizationStartEpoch=2]]] speechTrain=[reader=[readerType="HTKDeserializers"]]"
ExitCode=$?
sed 's/^/MPI Rank 0: /' $TEST_RUN_DIR/"$LogFileName"_speechTrain.logrank0
sed 's/^/MPI Rank 1: /' $TEST_RUN_DIR/"$LogFileName"_speechTrain.logrank1
exit $ExitCode
