#!/bin/bash

. $TEST_DIR/../run-test-common

OriginalTestDir=../CuDNN

(cd $TEST_DIR/$OriginalTestDir && md5sum baseline*) | (cd $TEST_DIR && md5sum --status -c -)
if [ $? != 0 ]; then
  echo Error: Baselines must match original test. Copy from $OriginalTestDir.
  exit 1
fi

cntkrun 02_BatchNormConv.cntk batchNormalizationEngine=cntk
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
