#!/bin/bash

. $TEST_DIR/../run-test-common

ConfigDir=$TEST_DIR/../../../../../../../Examples/Image/Classification/GoogLeNet/InceptionV3/BrainScript

# need to modify learning rate, or I'm getting Nan. 
cntkrun InceptionV3.cntk "forceDeterministicAlgorithms=true traceLevel=0 stderr=- Train=[SGD=[epochSize=4,minibatchSize=2,maxEpochs=2,numMBsToShowResult=1,learningRatesPerMB=0.1]] Eval=[minibatchSize=2]"
