#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/../../../../../../Examples/Speech/AN4/Config

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun LSTM-NDL.config "speechTrain=[SGD=[maxEpochs=1]] speechTrain=[SGD=[epochSize=64]] parallelTrain=false" || exit $?

