#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/../../../../../../Examples/Other/Simple2d/Config

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun Simple.cntk "Simple_Demo_Train=[SGD=[maxEpochs=3]]" || exit $?

