#!/bin/bash

. $TEST_DIR/../run-test-common

# cntkrun <CNTK config file name> <additional CNTK args>
# Note: explicitly turn off randomization, as it crashes the reader.
cntkrun 04_ResNet_56_ndl_deprecated.cntk "Train=[SGD=[maxEpochs=1]] Train=[SGD=[epochSize=128]] Train=[reader=[randomize=none]] Train=[SGD=[minibatchSize=16]] Test=[minibatchSize=16] stderr=-"
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
