#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# Copy pretrained models and data
ImageDir=$TEST_ROOT_DIR/../../Examples/Image
MnistDir=$ImageDir/MNIST
DataDir=$MnistDir/Data
ConfigDir=$MnistDir/Config
OutputDir=$MnistDir/Output

cleanupAndExit()
{
  #Delete Model data
  rm -rf $OutputDir  
  exit $1
}

# Train model for evaluation
[ -d $OutputDir ] || mkdir $OutputDir || cleanupAndExit 1
[ -d $OutputDir/Models ] && rm -rf $OutputDir/Models
DeleteModelsAfterTest=0

[ -f $ConfigDir/01_OneHidden.cntk ] || cleanupAndExit 1

cntkrun 01_OneHidden.cntk "command=trainNetwork trainNetwork=[SGD=[maxEpochs=1]]" || cleanupAndExit 1
 
if [ "$OS" == "Windows_NT" ]; then
  $TEST_BIN_DIR/CPPEvalClientTest.exe
else
  $TEST_BIN_DIR/cppevalclient
fi

cleanupAndExit $?

