#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# Copy pretrained models and data
ImageDir=$TEST_ROOT_DIR/../../Examples/Image
MnistDir=$ImageDir/MNIST
DataDir=$MnistDir/Data
ConfigDir=$MnistDir/Config
OutputDir=$MnistDir/Output

# Train model for evaluation
[ -d $OutputDir ] || mkdir $OutputDir || exit 1
[ -d $OutputDir/Models ] && rm -rf $OutputDir/Models
DeleteModelsAfterTest=0

[ -f $ConfigDir/01_OneHidden.cntk ] || exit 1
[ -f $ConfigDir/02_Convolution.cntk ] || exit 1

cntkrun 01_OneHidden.cntk "command=trainNetwork trainNetwork=[SGD=[maxEpochs=1]]" || exit 1
 
if [ "$OS" == "Windows_NT" ]; then
  $TEST_BIN_DIR/CPPEvalClientTest.exe
else
  $TEST_BIN_DIR/cppevalclient
fi

ExitCode=$?

#Delete Model data
rm -rf $OutputDir

exit $ExitCode

