#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../SVD
ConfigDir=$TEST_DIR/$OriginalTestDir

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'reader=[readerType=ExperimentalHTKMLFReader] reader=[prefetch=true]' || exit $?
