#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../QuickE2E
ConfigDir=$TEST_DIR/$OriginalTestDir

(cd $TEST_DIR/$OriginalTestDir && md5sum baseline*) | (cd $TEST_DIR && md5sum --status -c -)
if [ $? != 0 ]; then
  echo Error: Baselines must match original test.
  exit 1
fi

# cntkrun <CNTK config file name> <additional CNTK args>
DeleteModelsAfterTest=0
cntkrun cntk.cntk 'reader=[readerType=ExperimentalHTKMLFReader] reader=[prefetch=true]' || exit $?
echo === Deleting last epoch data
rm $TEST_RUN_DIR/models/*.dnn
echo ==== Re-running from checkpoint
DeleteExistingModels=0
DeleteModelsAfterTest=1
# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'makeMode=true reader=[readerType=ExperimentalHTKMLFReader] reader=[prefetch=true]' || exit $?
