#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.config || exit $?
echo === Deleting last epoch data
rm $TEST_RUN_DIR/models/*.dnn
echo ==== Re-running from checkpoint
DeleteExistingModels=0
# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.config 'makeMode=true' || exit $?
