#!/bin/bash

. $TEST_DIR/../run-test-common

cntkrun 03_OneConvDropout.cntk "forceDeterministicAlgorithms=true stderr=- trainNetwork=[SGD=[maxEpochs=3]]"
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
