#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

set -x

PythonVer=$(python -c "import sys; print(sys.version_info[0])")
if [ "$PythonVer" == "3" ]; then
	echo Skip this test for Python 3.4/3.5. Run this test only on Python 2.7 to save test time. 
	exit 0
fi

# This test uses a large dataset which is not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
if [[ "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" == "" || ! -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
  echo 'This test uses external data that is not part of the CNTK repository. Environment variable CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY must be set to point to the external test data location'
  exit 1
fi

if [ "$OS" == "Windows_NT" ]; then
    DataSourceDir=`cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY`/Image
else
    DataSourceDir=$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY/Image
fi

# Copy the test data to the test run directory
TestDataDir=$TEST_RUN_DIR/TestData
mkdir $TestDataDir


# Train ResNet CIFAR-10 model.
ScriptDir=$TEST_ROOT_DIR/../../Examples/Image/Classification/ResNet/Python
DataDir=$TEST_ROOT_DIR/../../Examples/Image/DataSets/CIFAR-10
cp $DataSourceDir/CIFAR/v0/cifar-10-batches-py/*.txt $DataDir || exit $?
cp $DataSourceDir/CIFAR/v0/cifar-10-batches-py/*.xml $DataDir || exit $?
[ -f $ScriptDir/Models/resnet20_0.dnn ] || exit 1
python TrainResNet_CIFAR10.py -e 1 || exit $?
cp $ScriptDir/Models/resnet20_0.dnn $TestdataDir/resnet20.dnn || exit $?


# Train ATIS model 
ScriptDir=$TEST_ROOT_DIR/../../Examples/LanguageUnderstanding/ATIS/Python
[ -f $ScriptDir/Models/atis_0.dnn ] || exit 1
python LanguageUnderstanding.py -e 1 || exit $?
cp $ScriptDir/Models/atis_0.dnn $TestdataDir/atis.dnn || exit $?
cp $ScriptDir/../BrainScript/query.wl $TestdataDir || exit $?
cp $ScriptDir/../BrainScript/slots.wl $TestdataDir || exit $?

# Set CUDA_VISIBLE_DEVICES to exclude all gpu if running on cpu device
if [ "$TEST_DEVICE" == "cpu" ]; then
  export CUDA_VISIBLE_DEVICES=-1
fi

pushd $TestDataDir

if [ "$OS" == "Windows_NT" ]; then
  $TEST_BIN_DIR/CNTKLibraryCSEvalExamplesTest.exe
else
  echo Cannot run CNTKLibraryCSEvalExampleTest on Linux.
  exit 1
fi

ExitCode=$?

# Delete the test data
popd
rm -rf $TestDataDir

if [ "$TEST_DEVICE" == "cpu" ]; then
  unset CUDA_VISIBLE_DEVICES
fi

exit $ExitCode
