#!/bin/bash

. $TEST_DIR/../run-test-common

cntkrun 01_OneHidden.cntk batchNormalizationEngine=cudnn
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
