#!/bin/bash

. $TEST_DIR/../run-test-common
ConfigDir=$TEST_DIR/../../../../../../Examples/Image/MNIST/Config/Ndl_deprecated

cntkrun  02_Convolution_ndl_deprecated.cntk  "forceDeterministicAlgorithms=true train=[SGD=[maxEpochs=3]] imageLayout=\"$imageLayout\" stderr=-"

ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
