#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

python -c "import sys; print('Python: %s'%sys.version)"
python -c "import numpy; print('NumPy: %s'%numpy.version.full_version)"
python -c "import scipy; print('SciPy: %s'%scipy.version.full_version)"
python -c "import pytest; print('PyTest: %s'%pytest.__version__)"

# TODO why doesn't "py.test --pyargs cntk" work?
MODULE_DIR="$(python -c "import cntk, os, sys; sys.stdout.write(os.path.dirname(os.path.abspath(cntk.__file__)))")"
[ $? -eq 0 ] || exit $?
py.test "$MODULE_DIR" --verbose --deviceid $TEST_DEVICE -k "not test_svd_factorization and not test_factor_dense and not test_free_static_axis_times_free_static_axis and not test_unpack_axis_times_transpose_unpack_axis and not test_op_batch_times and not test_op_times"

if [ "$?" -eq "0" ]; then
  echo "__COMPLETED__"
fi
