#!/bin/bash

export MKL_NUM_THREADS=4
export MKL_CBWR=COMPATIBLE
export OMP_NUM_THREADS=1

. $TEST_DIR/../run-test-common

cntkrun  01_OneHidden.cntk "forceDeterministicAlgorithms=true stderr=- trainNetwork=[SGD=[maxEpochs=3]]"
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
