#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/../../../../../../Examples/Image/MNIST/Config
if [ "$OS" == "Windows_NT" ]; then
  CleanDataDir=$(cygpath -aw $DataDir)
else
  CleanDataDir=$DataDir
fi

# cntkrun <CNTK config file name> <additional CNTK args>
imageLayout=cudnn

cntkrun 01_OneHidden.cntk  "MNISTtrain=[reader=[file=$CleanDataDir/Train.txt]]  MNISTtest=[reader=[file=$CleanDataDir/Test.txt]]  MNISTtrain=[SGD=[maxEpochs=1]]  MNISTtrain=[SGD=[epochSize=100]]  MNISTtrain=[reader=[randomize=none]]  imageLayout=\"$imageLayout\"" || exit $?

