#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# specific TIMIT variables
. $TEST_DIR/../run-timit-test-common

cntkrun TIMIT_TrainAutoEncoder_ndl_deprecated.cntk "$CntkArguments TIMIT_TrainAutoEncoder=[reader=[useMersenneTwisterRand=true]]" || exit $?
