FROM ubuntu:16.04

# Set up fake user / sudo environment:

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo lsb-release

RUN adduser --gecos "Test User" --disabled-password testuser && \
    test -d /home/testuser

COPY visudo-helper.sh prep-testenv.sh /root/

RUN VISUAL=/root/visudo-helper.sh visudo

COPY test_wrapper.sh /home/testuser
COPY BinaryDrops-CPU.tar.gz /home/testuser
RUN chown -R testuser:testuser /home/testuser

# TODO run repeated
RUN su - testuser -c "./test_wrapper.sh BinaryDrops-CPU.tar.gz"
