#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/..

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun OneHidden.cntk "Simple_Demo_Train=[SGD=[maxEpochs=3]]" || exit $?

