#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

if [ "$OS" == "Windows_NT" ]; then
  TestDataDir=`cygpath -aw $TEST_ROOT_DIR`/../../
  pushd $TEST_BIN_DIR > /dev/null
else
  TestDataDir=$TEST_ROOT_DIR/../../
  pushd $TEST_BIN_DIR/../lib > /dev/null
fi
dotnet CNTKLibraryCSTrainingTest.dll LSTMSequenceClassifierTest $TestDataDir
popd > /dev/null

ExitCode=$?

exit $ExitCode
