#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../../LSTM/Truncated
ConfigDir=$TEST_DIR/../../../LSTM

(cd $TEST_DIR/$OriginalTestDir && md5sum baseline*) | (cd $TEST_DIR && md5sum --status -c -)
if [ $? != 0 ]; then
  echo Error: Baselines must match original test.
  exit 1
fi

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'speechTrain=[reader=[readerType=ExperimentalHTKMLFReader]]' || exit $?
