#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# specific TIMIT variables
. $TEST_DIR/../run-timit-test-common

cntkrun TIMIT_TrainWithPreTrain_ndl_deprecated.cntk "$CntkArguments reader=[useMersenneTwisterRand=true]" || exit $?
