#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# specific TIMIT variables
. $TEST_DIR/../run-test-common

Sgd=`echo SGD=[{maxEpochs=1,epochSize=2048}]`
Train3Sgd=`echo TIMIT_Train3=[SGD=[{maxEpochs=1,epochSize=2048}]]`
CntkArguments+=" $Sgd $Train3Sgd reader=[verbosity=0] numMBsToShowResult=5"

# cntkrun <CNTK config file name> <additional CNTK arg>
cntkrun TIMIT_TrainWithPreTrain.cntk "$CntkArguments"
ExitCode=$?

exit $ExitCode