#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../SVD
ConfigDir=$TEST_DIR/$OriginalTestDir

(cd $TEST_DIR/$OriginalTestDir && md5sum baseline*) | (cd $TEST_DIR && md5sum --status -c -)
if [ $? != 0 ]; then
  echo Error: Baselines must match original test. Copy from $OriginalTestDir.
  exit 1
fi

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'reader=[readerType=HTKDeserializers]' || exit $?
