#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/../../../../../../Examples/Image/MNIST/Config
CleanDataDir=$(cygpath -aw $DataDir)

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun 03_ConvBatchNorm.config "train=[reader=[file=$CleanDataDir/Train.txt]] test=[reader=[file=$CleanDataDir/Test.txt]] train=[SGD=[maxEpochs=1]] train=[SGD=[epochSize=128]] train=[reader=[randomize=none]]" || exit $?

