#!/bin/bash

. $TEST_DIR/../run-test-common

cntkrun 03_ConvBatchNorm.cntk  "forceDeterministicAlgorithms=true stderr=-"
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
