#!/bin/bash

export MKL_NUM_THREADS=4
export MKL_CBWR=COMPATIBLE
export OMP_NUM_THREADS=1

. $TEST_DIR/../run-test-common

cntkrun 03_ConvBatchNorm.cntk  "forceDeterministicAlgorithms=true stderr=-"
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
