#!/bin/bash

. $TEST_DIR/../run-test-common

cntkrun $CNTKTextConfigDir/03_ConvBatchNorm.cntk  "train=[SGD=[maxEpochs=3]] imageLayout=\"$imageLayout\""
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
