#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# specific TIMIT variables
. $TEST_DIR/../run-test-common

Sgd=`echo TIMIT_TrainMultiTask=[SGD=[{maxEpochs=1,epochSize=2048}]]`
CntkArguments+=" $Sgd reader=[verbosity=0] numMBsToShowResult=5"

# cntkrun <CNTK config file name> <additional CNTK arg>
cntkrun TIMIT_TrainMultiTask.cntk "$CntkArguments"
ExitCode=$?

exit $ExitCode