#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

PYBINDINGDIR=$TEST_ROOT_DIR/../../bindings/python

pushd $PYBINDINGDIR
echo Current dir: $PYBINDINGDIR

python -c "import sys; print('Python: %s'%sys.version)"
python -c "import numpy; print('NumPy: %s'%numpy.version.full_version)"
python -c "import scipy; print('SciPy: %s'%scipy.version.full_version)"
python -c "import pytest; print('PyTest: %s'%pytest.__version__)"

cd $PYBINDINGDIR
py.test
# TODO --deviceid $TEST_DEVICE

if [ "$?" -eq "0" ]; then
  echo "__COMPLETED__"
fi

popd
