#!/bin/bash

. $TEST_ROOT_DIR/run-test-common
#On Linux the dlls are built into build/$config/lib directory
if [ "$OS" == "Windows_NT" ]; then
  pushd $TEST_BIN_DIR > /dev/null
else
  pushd $TEST_BIN_DIR/../lib > /dev/null
fi

dotnet CNTKLibraryCSTrainingTest.dll LogisticRegressionTest
popd > /dev/null

ExitCode=$?

exit $ExitCode
