#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# The eval test uses some pretrained models which is not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
if [[ "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" == "" || ! -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
  echo 'This test uses external data that is not part of the CNTK repository. Environment variable CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY must be set to point to the external test data location'
  exit 1
fi

if [ "$OS" == "Windows_NT" ]; then
    TestDataDir=`cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY`
else
    TestDataDir=$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY
fi

if [ "$OS" == "Windows_NT" ]; then

  # Copy pretrained models and data
  ImageDir=$TEST_ROOT_DIR/../../Examples/Image
  MnistDir=$ImageDir/MNIST
  DataDir=$MnistDir/Data
  ConfigDir=$MnistDir/Config
  OutputDir=$MnistDir/Output
  ResnetModelDir=$ImageDir/Miscellaneous/ImageNet/ResNet

  cp $TestDataDir/Image/MNIST/v0/Test-28x28_cntk_text.txt $DataDir || exit $?
  cp $TestDataDir/PreTrainedModels/ResNet_18.model $ResnetModelDir/ || exit $?

  # Train model for evaluation
  [ -d $OutputDir ] || mkdir $OutputDir || exit 1
  [ -d $OutputDir/Models ] && rm -rf $OutputDir/Models
  DeleteModelsAfterTest=0

  [ -f $ConfigDir/01_OneHidden.cntk ] || exit 1
  [ -f $ConfigDir/02_Convolution.cntk ] || exit 1

  cntkrun 01_OneHidden.cntk "command=trainNetwork trainNetwork=[SGD=[maxEpochs=1]]" || exit 1
  cntkrun 02_Convolution.cntk "command=trainNetwork trainNetwork=[SGD=[maxEpochs=1]]" || exit 1

  # Run the evaluation test
  cd $TEST_BIN_DIR
  ./CSEvalClientTest.exe || exit $?

  # Check whether any exceptions encountered
  grep -i "Inner Exception" $TEST_RUN_DIR/output.txt && exit 1
  ExitCode=0

  #Delete Model data
  rm -rf $OutputDir
  rm -f $DataDir/Test-28x28_cntk_text.txt
  rm -f $ResnetModelDir/ResNet_18.model

  exit $ExitCode

else
  echo "CSEvalClientTest can only run on Windows";
  exit 1;
fi