#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# specific TIMIT variables
. $TEST_DIR/../run-test-common

# cntkrun <CNTK config file name> <additional CNTK arg>
cntkrun TIMIT_TrainSimpleNetwork.cntk "LibDir=$LibDir ScpDir=$ScpDir MlfDir=$MlfDir NdlDir=$ConfigDir MelDir=$ConfigDir ExpDir=$ExpDir DeviceNumber=$DeviceNumber TIMIT_TrainSimple=[SGD=[maxEpochs=2]] TIMIT_TrainSimple=[SGD=[epochSize=20000]]"
ExitCode=$?

exit $ExitCode