#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

ConfigDir=$TEST_DIR/../../../../../../../Examples/Image/Miscellaneous/CIFAR-10

# This test uses a large dataset which is not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
echo Looking for data in: $TEST_DATA_DIR
if [[ ! -d $TEST_DATA_DIR || ! -e $TEST_DATA_DIR/cifar-10-batches-py ]]; then
    # Cannot find test data locally.
    # Try external test data directory (not part of the CNTK repository) as an alternative.
    if [ "$OS" == "Windows_NT" ]; then
        ExternalDataSourceDir=`cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY`
    else
        ExternalDataSourceDir=$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY
    fi

    echo Looking for data in: $ExternalDataSourceDir
    if [[ -d "$ExternalDataSourceDir" ]]; then
        DataSourceDir=$ExternalDataSourceDir/Image/CIFAR/v0

        # Copy the test data to the test run directory
        echo 'Copying test data to local directory'
        CopyDir=$TEST_RUN_DIR/cifar-10-batches-py
        mkdir $CopyDir
		# copying recursively also copies the unpacked zip
		# copying * results in exit code 0 due to omitting the directory
        cp $DataSourceDir/cifar-10-batches-py/*.xml $CopyDir || exit $?
        cp $DataSourceDir/cifar-10-batches-py/*.zip $CopyDir || exit $?
        cp $DataSourceDir/cifar-10-batches-py/*.txt $CopyDir || exit $?
        Copied=1
        echo 'Done copying data'
    else
        echo Error: cannot find data. Please see Examples/Image/Miscellaneous/CIFAR-10/README.md for instructions to get it.
        exit 1
    fi
fi

# cntkrun <CNTK config file name> <additional CNTK args>
# setting the DataDir to the run dir, since the cntk config expects data and mapping files in '$dataDir$/cifar-10-batches-py/'
DataDir=$TEST_RUN_DIR
echo 'Starting cntk run'
cntkrun 06_RegressionSimple.cntk "[command=TrainConvNet:Test] forceDeterministicAlgorithms=true stderr=-"
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$CopyDir"

exit $ExitCode
