#!/bin/bash

. $TEST_DIR/../run-test-common

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun 02_BatchNormConv.cntk "Train=[SGD=[maxEpochs=5]] Train=[SGD=[epochSize=100]] stderr=-"
ExitCode=$?

# Delete the test data if copied
[[ "$Copied" -eq "1" ]] && rm -rf "$DataDir"

exit $ExitCode
