#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

# cntkrun <CNTK config file name> <additional CNTK args>
DeleteModelsAfterTest=0
cntkrun seqcla.cntk || exit $?
echo === Deleting last epoch data
rm $TEST_RUN_DIR/models/*.dnn
echo ==== Re-running from checkpoint
DeleteExistingModels=0
DeleteModelsAfterTest=1
# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun seqcla.cntk 'makeMode=true' || exit $?
