(or (= (ICONST) 42) (exit 1))
(display "ICONST  = ")(display (ICONST))(display " (should be 42)\n")
(or (< (abs (- (FCONST) 2.1828)) 0.00001) (exit 1))
(display "FCONST  = ")(display (FCONST))(display " (should be 2.1828)\n")
(or (char=? (CCONST) #\x) (exit 1))
(display "CCONST  = ")(display (CCONST))(display " (should be 'x')\n")
(or (char=? (CCONST2) #\newline) (exit 1))
(display "CCONST2 = ")(display (CCONST2))(display " (this should be on a new line)\n")
(or (string=? (SCONST) "Hello World") (exit 1))
(display "SCONST  = ")(display (SCONST))(display " (should be 'Hello World')\n")
(or (string=? (SCONST2) "\"Hello World\"") (exit 1))
(display "SCONST2 = ")(display (SCONST2))(display " (should be \"Hello World\")\n")
(or (< (abs (- (EXPR) (+ (ICONST) (* 3 (FCONST))))) 0.00001) (exit 1))
(display "EXPR    = ")(display (abs (- (EXPR) (+ (ICONST) (* 3 (FCONST))))))(display " (should round to 0.0)\n")
(or (= (iconst) 37) (exit 1))
(display "iconst  = ")(display (iconst))(display " (should be 37)\n")
(or (< (abs (- (fconst) 3.14)) 0.00001) (exit 1))
(display "fconst  = ")(display (fconst))(display " (should be 3.14)\n")
(exit 0)
