#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../../LSTM/Truncated
ConfigDir=$TEST_DIR/../../../LSTM

checkOriginalBaseline $TEST_DIR $OriginalTestDir

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'speechTrain=[reader=[readerType=HTKDeserializers]] speechTrain=[SGD=[momentumAsTimeConstant=0:6074.9]] modelSelector=0' || exit $?
