#!/bin/bash
#
# Copyright (c) Microsoft. All rights reserved.
#
# Licensed under the MIT license. See LICENSE.md file in the project root
# for full license information.
# ==============================================================================

. $TEST_ROOT_DIR/run-test-common

set -x -o pipefail -e

MODULE_DIR="$(python -c "import cntk, os, sys; sys.stdout.write(os.path.dirname(os.path.abspath(cntk.__file__)))")"

cd ../../../../bindings/python/doc

sphinx-apidoc "$MODULE_DIR" -o . -f $(find "$MODULE_DIR" -type d -name tests)
make html SPHINXOPTS="-W -j $(nproc)"

set +x
echo "__COMPLETED__"
