#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

set -x

if [ "$OS" != "Windows_NT" ]; then
	echo 'This UWP test only runs on Windows.'
	exit 1
fi

# This test uses a large dataset which is not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
if [[ "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" == "" || ! -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
  echo 'This test uses external data that is not part of the CNTK repository. Environment variable CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY must be set to point to the external test data location'
  exit 1
fi

TEST_DATA_DIR=$(cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY)

VSTEST_CONSOLE=$(cygpath -au "$VS140COMNTOOLS\\..\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe")

test -x "$VSTEST_CONSOLE" || exit $?

# Use pretrained model
MODEL_FILE_DIR=$(cygpath -au "$HOMEPATH\\Documents")
cp $TEST_DATA_DIR/PreTrainedModels/EvalModels/01_OneHidden $MODEL_FILE_DIR/01_OneHidden || exit $?
ls $MODEL_FILE_DIR

# Set CUDA_VISIBLE_DEVICES to exclude all gpu if running on cpu device
[ "$TEST_DEVICE" == "cpu" ] && export CUDA_VISIBLE_DEVICES=-1

"$VSTEST_CONSOLE" /inIsolation /Platform:x64 $(cygpath -aw "$TEST_BIN_DIR/CNTKLibraryCPPUWPEvalExamplesTests/CNTKLibraryCPPUWPEvalExamplesTests_1.0.1.0_x64_"$TEST_FLAVOR"_UWP.appx") || exit $?


rm -rf $MODEL_FILE_DIR/01_OneHidden || exit $?
if [[ -f "$MODEL_FILE_DIR/01_OneHidden" ]]; then
  echo "Failed to delete the model file $MODEL_FILE_DIR/01_OneHidden"
  exit 1
fi
ls $MODEL_FILE_DIR
  
exit 0
