#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../../../Examples/Speech/TIMIT/TrainLstm

# Note: can directly use run-timit-test-common since it lives at the same level
# in the directory hierarchy.
. $TEST_DIR/$OriginalTestDir/../run-timit-test-common

checkOriginalBaseline $TEST_DIR $OriginalTestDir

# Running only 3 epochs (~1000s gpu release), because full run takes a lot of time.
cntkrun TIMIT_TrainLSTM_ndl_deprecated.cntk "$CntkArguments TIMIT_TrainLSTM=[cvReader=[readerType=HTKDeserializers]] TIMIT_TrainLSTM=[reader=[readerType=HTKDeserializers]] TIMIT_TrainLSTM=[SGD=[maxEpochs=3]]" || exit $?
