#!/bin/bash

cd ../../..

downloaders=(
  Examples/Image/DataSets/Animals/install_animals.py
  Examples/Image/DataSets/CIFAR-10/install_cifar10.py
  Examples/Image/DataSets/Flowers/install_flowers.py
  Examples/Image/DataSets/Grocery/install_grocery.py
  Examples/Image/DataSets/MNIST/install_mnist.py
  Examples/Image/DataSets/Pascal/install_pascalvoc.py
)

function exitWithError {
  set +e +x
  printf "$@" 1>&2
  exit 1
}

set -x

# Test for existence and clean
for p in "${downloaders[@]}"; do
  [[ -f $p ]] || exitWithError "File %s does not exist.\n" "$p"
  git clean -fdx "$(dirname "$p")" || exitWithError "Git clean for %s failed.\n" "$p"
done

ERRORS=0
for p in "${downloaders[@]}"; do
  python "$p" || {
    echo Error: running $p failed
    ((ERRORS++))
  }
done

if ((ERRORS != 0)); then
  echo $ERRORS occurred.
  exit 1
else
  set +x
  echo __COMPLETED__
fi
