#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

set -x

# This test uses a large dataset which is not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
if [[ "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" == "" || ! -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
  echo 'This test uses external data that is not part of the CNTK repository. Environment variable CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY must be set to point to the external test data location'
  exit 1
fi

if [ "$OS" == "Windows_NT" ]; then
    DataSourceDir=`cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY`/Image
else
    DataSourceDir=$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY/Image
fi

# Copy the test data to the test run directory
TestDataDir=$TEST_RUN_DIR/TestData
mkdir $TestDataDir

# Setup predefined variables $DataDir, $ConfigDir, and $OutputDir that are required by cntkrun
ConfigDir=$TEST_ROOT_DIR/../../Examples/Image/GettingStarted
OutputDir=$ConfigDir/Output
DataDir=$ConfigDir/../DataSets/MNIST

cp $DataSourceDir/MNIST/v0/Train-28x28_cntk_text.txt $DataDir || exit $?

# Train model that is needed by evaluation
[ -d $OutputDir ] || mkdir $OutputDir || exit $?
[ -d $OutputDir/Models ] && rm -rf $OutputDir/Models
DeleteModelsAfterTest=0
[ -f $ConfigDir/01_OneHidden.cntk ] || exit 1
cntkrun 01_OneHidden.cntk "stderr=- command=trainNetwork trainNetwork=[SGD=[maxEpochs=1]]" || exit $?
cp $OutputDir/Models/01_OneHidden $TestDataDir || exit $?

# Set CUDA_VISIBLE_DEVICES to exclude all gpu if running on cpu device
if [ "$TEST_DEVICE" == "cpu" ]; then
  export CUDA_VISIBLE_DEVICES=-1
fi

pushd $TestDataDir

if [ "$OS" == "Windows_NT" ]; then
  $TEST_BIN_DIR/CNTKLibraryCPPEvalExamplesTest.exe
else
  $TEST_BIN_DIR/CNTKLibraryCPPEvalExamplesTest
fi

ExitCode=$?

# Delete the test data
popd
rm -rf $TestDataDir

exit $ExitCode
