#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../../DNN/DiscriminativePreTraining
ConfigDir=$TEST_DIR/$OriginalTestDir

checkOriginalBaseline $TEST_DIR $OriginalTestDir

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk_dpt.cntk 'reader=[readerType=HTKDeserializers]' || exit $?
