#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

set -x

# This test uses a large dataset which is not part of the CNTK repository itself
# We use the dataset from an external location specified using an environment variable
if [[ "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" == "" || ! -d "$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY" ]]; then
  echo 'This test uses external data that is not part of the CNTK repository. Environment variable CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY must be set to point to the external test data location'
  exit 1
fi

if [ "$OS" == "Windows_NT" ]; then
    DataSourceDir=`cygpath -au $CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY`/Image
else
    DataSourceDir=$CNTK_EXTERNAL_TESTDATA_SOURCE_DIRECTORY/Image
fi

# Copy the test data to the test run directory
TestDataDir=$TEST_RUN_DIR/TestData
mkdir $TestDataDir
cp -R $DataSourceDir/CIFAR/v0/cifar-10-batches-py $TestDataDir || exit $?

# Set CUDA_VISIBLE_DEVICES to exclude all gpu if running on cpu device
[ "$TEST_DEVICE" == "cpu" ] && export CUDA_VISIBLE_DEVICES=-1

pushd $TestDataDir

if [ "$OS" == "Windows_NT" ]; then
  $TEST_BIN_DIR/V2LibraryEndToEndTests.exe CifarResNet
else
  $TEST_BIN_DIR/V2LibraryEndToEndTests CifarResNet
fi

ExitCode=$?

# Delete the test data
popd
rm -rf $TestDataDir

exit $ExitCode
